spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://dpg-ctk7ajhopnds73fspjug-a.oregon-postgres.render.com:5432/orderdb_4trg
    username: orderdb_4trg_user
    password: ATBD5SRA6LbNmqzcAMALGGgB9MVxq3Hx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  profiles:
    active: dev

kafka:
  bootstrap-servers: localhost:9092
  
server:
  port: 8080
